# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  build:
    environment:
      ENDPOINT_URL: https://idling.host
    docker:
      - image: circleci/ruby:2.3
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: install dependencies
          command: |
            sudo -- bash -c 'yes | apt-get install rsync nodejs'
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: middleman build
          command:
            bundle exec middleman build
      - run:
          name: deploy to prod
          command: |
            mkdir ~/.ssh || rm -f ~/.ssh/known_hosts
            mv ./.circleci/known_hosts ~/.ssh/
            ./deploy.sh
